# Generated by Django 3.0.6 on 2020-05-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=250)),
                ('book_author', models.CharField(max_length=250)),
                ('book_publisher', models.CharField(max_length=300)),
                ('book_image', models.FileField(upload_to='')),
            ],
        ),
    ]
